name: Deploy to Vercel

on:
  workflow_dispatch:
    inputs:
      user_name:
        description: "Name of the user triggering the deployments"
        required: true
        default: "Anonymous"

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      USER_NAME: ${{ github.event.inputs.user_name }}

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js for testing
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Step 3: Install dependencies and run tests
      - name: Install dependencies and run tests
        run: |
          echo "Running tests for user: $USER_NAME"
          npm install
          npm run test

      # Step 4: Deploy to Vercel
      - name: Deploy to Vercel
        run: |
          curl -X POST "https://api.vercel.com/v10/projects" \
            -H "Authorization: Bearer $VERCEL_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
                "name": "ephimeral-project-'$USER_NAME'",
                "buildCommand": "npm run build",
                "environmentVariables": [
                    {
                        "key": "USER_NAME",
                        "target": "production",
                        "type": "plain",
                        "value": "'$USER_NAME'"
                    }
                ],
                "gitRepository": {
                    "repo": "porfolio-pipeline",
                    "type": "github"
                },
                "installCommand": "npm install"
            }'

      # Step 5: Append the USER_NAME to names.txt
      - name: Append user name to names.txt
        run: |
          echo "$USER_NAME" >> names.txt
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add names.txt
          git commit -m "Add $USER_NAME to names.txt"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 6: Wait for 1 minutes
      - name: Wait for 2 minutes
        run: sleep 120

      # Step 7: Delete the deployment
      - name: Delete the deployment
        run: |
          curl -X DELETE "https://api.vercel.com/v9/projects/ephimeral-project-$USER_NAME" \
            -H "Authorization: Bearer $VERCEL_TOKEN" \
            -H "Content-Type: application/json"
