name: Deploy App

on:
  repository_dispatch:
    types: [deploy_app]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      CLIENT_NAME: ${{ github.event.client_payload.name }}

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js for tests
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install dependencies and run tests
      - name: Install dependencies and run tests
        run: |
          npm install
          npm test

      # Step 4: Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # Step 5: Build and push the Docker image
      - name: Build and push Docker image
        run: |
          docker build -t $DOCKERHUB_USERNAME/portfolio-app:${{ github.run_id }} .
          docker push $DOCKERHUB_USERNAME/portfolio-app:${{ github.run_id }}

      # Step 6: Deploy to Render
      - name: Deploy to Render
        run: |
          curl -X POST \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{
            "serviceId": "YOUR_RENDER_SERVICE_ID",
            "clearCache": false,
            "envVars": {
              "CLIENT_NAME": "'${{ github.event.client_payload.name }}'"
            },
            "image": "docker.io/'${{ secrets.DOCKERHUB_USERNAME }}/portfolio-app:${{ github.run_id }}'"
          }' \
          https://api.render.com/v1/services/YOUR_RENDER_SERVICE_ID/deploys
