name: Deploy to Vercel

on:
  workflow_dispatch:
    inputs:
      user_name:
        description: "Name of the user triggering the deployment"
        required: true
        default: "Anonymous"

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      USER_NAME: ${{ github.event.inputs.user_name }}

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js for testing
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Step 3: Install dependencies and run tests
      - name: Install dependencies and run tests
        run: |
          echo "Running tests for user: $USER_NAME"
          npm install
          npm run test

      # Step 4: Deploy to Vercel
      - name: Deploy to Vercel
        run: |
          curl -X POST "https://api.vercel.com/v10/projects" \
            -H "Authorization: Bearer $VERCEL_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
                "name": "ephimeral-project-'$USER_NAME'",
                "buildCommand": "npm run build",
                "environmentVariables": [
                    {
                        "key": "USER_NAME",
                        "target": "production",
                        "type": "system",
                        "value": "'$USER_NAME'"
                    }
                ],
                "gitRepository": {
                    "repo": "porfolio-pipeline",
                    "type": "github"
                },
                "installCommand": "npm install"
            }'
